### PR TITLE
Remove custom archive parsing; use `clap::value_enum`

### PR DESCRIPTION
**Pull request by mre**
Removes custom parsing code.
See https://github.com/lycheeverse/lychee/pull/1003#discussion_r1141926029.

### CODE REVIEW

**Comment by mre** [comment]
Hum. I don't know. Maybe with [PossibleValue](https://docs.rs/clap/latest/clap/builder/struct.PossibleValue.html).

**Comment by mre** [comment]
Works.

```bash
cargo run -- --archive notfound
error: invalid value 'notfound' for '--archive <ARCHIVE>'
  [possible values: wayback]

For more information, try '--help'.
```

and

```bash
--archive <ARCHIVE>
    Specify the use of a specific web archive. Can be used in combination with `--suggest`
    
    [possible values: wayback]
```

**Comment by mre** [comment]
From https://github.com/clap-rs/clap/discussions/4264.

**Comment by thomas-zahner** [comment]
Thank you that's really awesome, didn't find `PossibleValue` myself

**Pull request merged**
